// Code automatically generated by 'Generate Cone Mapping Model' script by Jolyon Troscianko

//Model fits:
//X 0.9974738406886285
//Y 0.998542097549333
//Z 0.9981446730593436


// Generated: 2025/8/11   12:16:0


import ij.*;
import ij.plugin.filter.PlugInFilter;
import ij.process.*;

public class Sony_a6000_CIE_XYZ_1931_D65_ implements PlugInFilter {

ImageStack stack;
	public int setup(String arg, ImagePlus imp) { 
	stack = imp.getStack(); 
	return DOES_32 + STACK_REQUIRED; 
	}
public void run(ImageProcessor ip) {

IJ.showStatus("Cone Mapping");
float[] visibleR;
float[] visibleG;
float[] visibleB;
int w = stack.getWidth();
int h = stack.getHeight();
int dimension = w*h;

float[] X = new float[dimension];
float[] Y = new float[dimension];
float[] Z = new float[dimension];

visibleR = (float[]) stack.getPixels(1);
visibleG = (float[]) stack.getPixels(2);
visibleB = (float[]) stack.getPixels(3);

for (int i=0;i<dimension;i++) {
X[i] = (float) (-0.005503935794902521 +(visibleR[i]*0.006111386918596263)+(visibleG[i]*0.001725878513078685)+(visibleB[i]*7.328346432096927E-4)+(visibleR[i]*visibleG[i]*1.613501541175441E-5)+(visibleR[i]*visibleB[i]*1.2596134491350824E-5)+(visibleG[i]*visibleB[i]*-1.7736006794285516E-5));
Y[i] = (float) (-0.005459988883889009 +(visibleR[i]*0.0016285558094244782)+(visibleG[i]*0.009483655645222409)+(visibleB[i]*-0.002342323968052441)+(visibleR[i]*visibleG[i]*6.597765369535931E-6)+(visibleR[i]*visibleB[i]*2.0426627764725488E-5)+(visibleG[i]*visibleB[i]*-1.7756548830791185E-5));
Z[i] = (float) (-0.004021457385384781 +(visibleR[i]*-3.083262897588199E-4)+(visibleG[i]*-0.002895739558919408)+(visibleB[i]*0.011623547639294287)+(visibleR[i]*visibleG[i]*2.205432744925796E-5)+(visibleR[i]*visibleB[i]*1.705408992503389E-5)+(visibleG[i]*visibleB[i]*-3.115634125585898E-5));
IJ.showProgress((float) i/dimension);
}

ImageStack outStack = new ImageStack(w, h);
outStack.addSlice("X", X);
outStack.addSlice("Y", Y);
outStack.addSlice("Z", Z);
new ImagePlus("Output", outStack).show();

}
}
