// Code automatically generated by 'Generate Cone Mapping Model' script by Jolyon Troscianko

//Model fits:
//lw 0.9984106408919764
//mw 0.9988196266417712
//sw 0.9976358270110941


// Generated: 2025/8/11   12:27:26


import ij.*;
import ij.plugin.filter.PlugInFilter;
import ij.process.*;

public class Sony_a6000_Human_D65_ implements PlugInFilter {

ImageStack stack;
	public int setup(String arg, ImagePlus imp) { 
	stack = imp.getStack(); 
	return DOES_32 + STACK_REQUIRED; 
	}
public void run(ImageProcessor ip) {

IJ.showStatus("Cone Mapping");
float[] visibleR;
float[] visibleG;
float[] visibleB;
int w = stack.getWidth();
int h = stack.getHeight();
int dimension = w*h;

float[] lw = new float[dimension];
float[] mw = new float[dimension];
float[] sw = new float[dimension];

visibleR = (float[]) stack.getPixels(1);
visibleG = (float[]) stack.getPixels(2);
visibleB = (float[]) stack.getPixels(3);

for (int i=0;i<dimension;i++) {
lw[i] = (float) (-0.005825470907339992 +(visibleR[i]*0.002804611914301557)+(visibleG[i]*0.007983033941205586)+(visibleB[i]*-0.0020264261269351213)+(visibleR[i]*visibleG[i]*6.683787089730198E-6)+(visibleR[i]*visibleB[i]*1.8210440217164747E-5)+(visibleG[i]*visibleB[i]*-1.5469707452319857E-5));
mw[i] = (float) (-0.0056143148318438234 +(visibleR[i]*-3.6290298844713064E-4)+(visibleG[i]*0.010927324126375013)+(visibleB[i]*-0.0017338990817803036)+(visibleR[i]*visibleG[i]*3.089332655730838E-6)+(visibleR[i]*visibleB[i]*2.238667806160005E-5)+(visibleG[i]*visibleB[i]*-1.734020176459498E-5));
sw[i] = (float) (-0.003464736147888664 +(visibleR[i]*-4.085784758676695E-4)+(visibleG[i]*-0.0031689852417152212)+(visibleB[i]*0.01194979705482504)+(visibleR[i]*visibleG[i]*2.2862055228458358E-5)+(visibleR[i]*visibleB[i]*3.168777800575095E-5)+(visibleG[i]*visibleB[i]*-4.707230080230361E-5));
IJ.showProgress((float) i/dimension);
}

ImageStack outStack = new ImageStack(w, h);
outStack.addSlice("lw", lw);
outStack.addSlice("mw", mw);
outStack.addSlice("sw", sw);
new ImagePlus("Output", outStack).show();

}
}
