// Code automatically generated by 'Generate Cone Mapping Model' script by Jolyon Troscianko

//Model fits:
//lw 0.9979843355323719
//mw 0.9992603121620205
//sw 0.9982967053682914
//dbl 0.9986248918642762


// Generated: 2025/8/10   12:27:29


import ij.*;
import ij.plugin.filter.PlugInFilter;
import ij.process.*;

public class Sony_a6400_Bluetit_LMS_D65_ implements PlugInFilter {

ImageStack stack;
	public int setup(String arg, ImagePlus imp) { 
	stack = imp.getStack(); 
	return DOES_32 + STACK_REQUIRED; 
	}
public void run(ImageProcessor ip) {

IJ.showStatus("Cone Mapping");
float[] visibleR;
float[] visibleG;
float[] visibleB;
int w = stack.getWidth();
int h = stack.getHeight();
int dimension = w*h;

float[] lw = new float[dimension];
float[] mw = new float[dimension];
float[] sw = new float[dimension];
float[] dbl = new float[dimension];

visibleR = (float[]) stack.getPixels(1);
visibleG = (float[]) stack.getPixels(2);
visibleB = (float[]) stack.getPixels(3);

for (int i=0;i<dimension;i++) {
lw[i] = (float) (-5.320097925075269E-4 +(visibleR[i]*0.012163893941337071)+(visibleG[i]*-0.001591185860534285)+(visibleB[i]*-7.351045703205806E-4)+(visibleR[i]*visibleG[i]*-1.1828414644628031E-5)+(visibleR[i]*visibleB[i]*6.595988121656493E-6)+(visibleG[i]*visibleB[i]*2.9298992769517796E-6));
mw[i] = (float) (0.0013088860001727893 +(visibleR[i]*-0.0016332246620673653)+(visibleG[i]*0.015112088345718557)+(visibleB[i]*-0.003677358631135649)+(visibleR[i]*visibleG[i]*4.3969944055267114E-7)+(visibleR[i]*visibleB[i]*3.0098716349905974E-5)+(visibleG[i]*visibleB[i]*-3.3232418284036425E-5));
sw[i] = (float) (0.0024676127258441444 +(visibleR[i]*-1.5453579080386542E-4)+(visibleG[i]*-0.002211426474071181)+(visibleB[i]*0.011376649436565352)+(visibleR[i]*visibleG[i]*1.2013496102585392E-5)+(visibleR[i]*visibleB[i]*2.096822715285254E-5)+(visibleG[i]*visibleB[i]*-3.3108375144723976E-5));
dbl[i] = (float) (-4.995521980486973E-4 +(visibleR[i]*0.00255750020057697)+(visibleG[i]*0.00759476880250606)+(visibleB[i]*-4.922603332441273E-4)+(visibleR[i]*visibleG[i]*-1.5184155604923655E-6)+(visibleR[i]*visibleB[i]*9.604046617680934E-6)+(visibleG[i]*visibleB[i]*-9.48512923871649E-6));
IJ.showProgress((float) i/dimension);
}

ImageStack outStack = new ImageStack(w, h);
outStack.addSlice("lw", lw);
outStack.addSlice("mw", mw);
outStack.addSlice("sw", sw);
outStack.addSlice("dbl", dbl);
new ImagePlus("Output", outStack).show();

}
}
